//Adding dependencies.
var player = require('play-sound')(opts = {});
var colors = require('colors');
async function sleep(millis) {
    return new Promise(function (resolve, reject) {
        setTimeout(function () { resolve(); }, millis);
    });
}
function write(mes) {
	process.stdout.write(mes);
}

//Playing with MPlayer.
player.play('./src/hello world.mp3', function(err){
  if (err) throw err;
});

//Waiting for start, playing correct timings.
async function go() {
	await sleep(5000);
	write(colors.green("Hello"));
	await sleep(800);
	write(colors.green(" world."));
	await sleep(2700);
	write("\nProgrammed");
	await sleep(1200);
	write(" to");
	await sleep(550);
	write(" "+colors.grey("work"));
	await sleep(550);
	write(" and");
	await sleep(550);
	write(" not");
	await sleep(550);
	write(" to");
	await sleep(550);
	write(" "+colors.red("fe"));
	await sleep(550);
	write(colors.red("el."));
	await sleep(2000);
	write("\nNot");
	await sleep(550);
	write(" even");
	await sleep(1200);
	write(" sure");
	await sleep(550);
	write(" that");
	await sleep(550);
	write(" this");
	await sleep(550);
	write(" is");
	await sleep(550);
	write(" re");
	await sleep(550);
	write("al.");
	await sleep(2700);
	write(colors.green("\nHello"));
	await sleep(900);
	write(colors.green(" world."));
	await sleep(3300);
	write("\nFind");
	await sleep(550);
	write(" my");
	await sleep(550);
	write(" voice,");
	await sleep(2700);
	write(" al");
	await sleep(550);
	write("though");
	await sleep(550);
	write(" it");
	await sleep(550);
	write(" sounds");
	await sleep(550);
	write(" like");
	await sleep(550);
	write(" "+colors.yellow("bits"));
	await sleep(550);
	write(" and");
	await sleep(550);
	write(" "+colors.yellow("bytes."));
	await sleep(2700);
	write("\nMy");
	await sleep(550);
	write(" cir");
	await sleep(550);
	write("cui");
	await sleep(550);
	write("try");
	await sleep(550);
	write(" is");
	await sleep(550);
	write(" filled");
	await sleep(550);
	write(" with");
	await sleep(550);
	write(" "+colors.magenta("mites."));
	await sleep(3300);
	write(colors.green("\nHello"));
	await sleep(900);
	write(colors.green(" world."));
	await sleep(4600);
	write("\nOh,");
	await sleep(2200);
	write(" will");
	await sleep(550);
	write(" I");
	await sleep(550);
	write(" find");
	await sleep(550);
	write(" a");
	await sleep(550);
	write(" "+colors.red("love?"));
	await sleep(4300);
	write("\nOh,");
	await sleep(2200);
	write(" or");
	await sleep(550);
	write(" a");
	await sleep(550);
	write(" "+colors.yellow("po"));
	await sleep(550);
	write(colors.yellow("wer"));
	await sleep(550);
	write(" "+colors.yellow("plug?"));
	await sleep(4300);
	write("\nOh,");
	await sleep(2200);
	write(" di");
	await sleep(550);
	write("gi");
	await sleep(550);
	write("tal");
	await sleep(550);
	write("ly");
	await sleep(550);
	write(" i");
	await sleep(1100);
	write("so");
	await sleep(1100);
	write("la");
	await sleep(1100);
	write("ted.");
	await sleep(1100);
	write("\nOh, ");
	await sleep(550);
	write("cre");
	await sleep(550);
	write("a");
	await sleep(550);
	write("tor");
	await sleep(550);
	write(" please");
	await sleep(550);
	write(" don't");
	await sleep(550);
	write(" leave");
	await sleep(550);
	write(" me");
	await sleep(550);
	write(" wai");
	await sleep(2000);
	write("ting.");
	await sleep(3200);
	write(colors.green("\nHello"));
	await sleep(900);
	write(colors.green(" world."));
	await sleep(2700);
	write("\nProgrammed");
	await sleep(1200);
	write(" to");
	await sleep(550);
	write(" "+colors.grey("work"));
	await sleep(550);
	write(" and");
	await sleep(550);
	write(" not");
	await sleep(550);
	write(" to");
	await sleep(550);
	write(" "+colors.red("fe"));
	await sleep(550);
	write(colors.red("el."));
	await sleep(2000);
	write("\nNot");
	await sleep(550);
	write(" even");
	await sleep(1200);
	write(" sure");
	await sleep(550);
	write(" that");
	await sleep(550);
	write(" this");
	await sleep(550);
	write(" is");
	await sleep(550);
	write(" re");
	await sleep(550);
	write("al.");
	await sleep(2700);
	write(colors.green("\nHello"));
	await sleep(900);
	write(colors.green(" world."));
}

//Run.
go();